plugins {
	id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
	mavenCentral()
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

dependencies {

	// ① Spring Boot BOM（必须第一行）
	implementation platform(project(":spring-boot-project:spring-boot-dependencies"))

	// Spring Boot 核心模块
	implementation project(":spring-boot-project:spring-boot")
//	implementation project(":spring-boot-project:spring-boot-autoconfigure")

	// ② Web Starter（唯一需要的 starter）
	implementation project(":spring-boot-project:spring-boot-starters:spring-boot-starter-web")

	// ③ Servlet API（编译期即可）
	compileOnly "javax.servlet:javax.servlet-api:4.0.1"

	// ❌ 不要自己指定 junit 版本（Boot 已经管理）
//	testImplementation project(":spring-boot-project:spring-boot-starter-test")
}

test {
	useJUnitPlatform()
}
